### ISSUE TITLE
Error after installing HA Core 2024.2.2

### ISSUE THREAD

**Issue by MichaelS1955** [CestLaGalere/mobilealerts#21]
Hi,
after update all entities are no longer available.
Any infos what I can do?

Regards
Michael

**This is the error log:**
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:344
Integration: Sensor (documentation, issues)
First occurred: 12:28:40 (1 occurrences)
Last logged: 12:28:40

Error while setting up mobile_alerts platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/mobile_alerts/sensor.py", line 430, in fetch_data
    async with session.post(url, data=json_data, headers=headers) as response:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 605, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 961, in start
    with self._timer:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/mobile_alerts/sensor.py", line 163, in _async_update_data
    return await self._mobile_alerts_data.fetch_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mobile_alerts/sensor.py", line 457, in fetch_data
    raise ApiError()
custom_components.mobile_alerts.sensor.ApiError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 313, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mobile_alerts/sensor.py", line 165, in _async_update_data
    raise UpdateFailed(f"Error communicating with API: {err}")
homeassistant.helpers.update_coordinator.UpdateFailed: Error communicating with API: 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/mobile_alerts/sensor.py", line 121, in async_setup_platform
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 285, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: Error communicating with API:

**Comment by MichaelS1955** [comment]
Hi,
its magic. I am getting again data.
Now HA is running on OS 12.0 and core 2024.2.3
